title: Mambodyssee
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 0.2473118
  rhythmicContrast: 0.25
  brandColors:
    - '#97bce9'
    - '#22231e'
    - '#5d6b78'
    - '#ddc59a'
    - '#e4ebf3'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-161492-4
  facebook: null
favicon: null
name: Mambodyssee
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.25519
layout_spectrum: 0.6953405
