name: Mambodyssee
favicon: null
layout_spectrum: 0.62154
typography_spectrum: 0.25519
title: Mambodyssee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-161492-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d5d5d5'
    - '#292929'
    - '#a7a7a7'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
