name: Mambodyssee
favicon: null
layout_spectrum: 0.72871
typography_spectrum: 0.25519
title: Mambodyssee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-161492-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97bce9'
    - '#22231e'
    - '#5d6b78'
    - '#ddc59a'
    - '#e4ebf3'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
