name: Mambodyssee
favicon: null
layout_spectrum: 0.36389
typography_spectrum: 0.25519
title: Mambodyssee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#281e1c'
    - '#9f7060'
    - '#d59d84'
    - '#800b26'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
